### ISSUE TITLE
Suggestion - Remove unused boilerplate

### ISSUE THREAD

**Issue by ulic75** [AnthonMS/my-cards#10]
There seems a lot of leftover, unused code from the boilerplate card.  I'd suggest that it be remove for two reasons:

1. It adds unnecessary bloat to the code, while the code base is still quite small, why make it larger than it needs to be.
2. If someone else starts developing their own card based on boilerplate they could encounter errors as there are some naming conflicts, for example the custom element 'boilerplate-card-editor' (which has not yet been implemented in my-cards).

IMO, removing this stuff would add more polish and professionalism.  I'd also suggest not combining two cards (slider & footer) together into one package.  It might be more convenient for your use, but not everyone will want both cards.

I'd be happy to submit a PR for removing the boilerplate stuff.  It's mostly just the editor.   But removing it saves 8K.

**Comment by AnthonMS** [comment]
Sorry about taking so long for a response. But thanks for letting me know and thanks for submitting the PR with the changes.
