### ISSUE TITLE
Suggestion - support for MQTT numbers

### ISSUE THREAD

**Issue by Handkep** [AnthonMS/my-cards#12]
I think the title says everything.
I need to controll my esp8266 via MQTT, but sadly, numbers are not supported.
![image](https://user-images.githubusercontent.com/67271136/149855735-a4dfbc92-8598-473e-89d1-5b8f040858d5.png)
It would be very nice if you could add this feature

**Comment by AnthonMS** [comment]
I can look into this the next time I'm working on the card. But what service is called when using a MQTT number entity? Is it also just input_number.set_value?

**Comment by somegeekintn** [comment]
I'd like to second this suggestion please! And it looks like it would use `number.set_value` as opposed to `input_number.set_value`.

**Comment by AnthonMS** [comment]
I apologize about being so terribly slow. I will look into adding this to the old slider as well as the new slider-v2. Hopefully I get around to it. There are so much I want to do.

**Comment by AnthonMS** [comment]
This should be resolved for both slider v1 & v2 in version 9692d2e.

Let me know if there are any problems with it. I haven't been able to find much documentation for the actions. So I trust blindly that it is action 'set_value' on entity type 'number' like the user above said. I trusdt that the number entity also has the attributes 'min', 'max' and 'step'. If they don't, then it might break. But I'm pretty sure it does.

But let me know.

**Comment by somegeekintn** [comment]
> I haven't been able to find much documentation for the actions. So I trust blindly that it is action 'set_value' on entity type 'number' like the user above said.
I've just been doing a search and replace of input_number with number as my workaround and it's been working fine so we should be good to go! Thanks!
