### ISSUE TITLE
When searching in HACS "my-cards" is not popping up.

### ISSUE THREAD

**Issue by Atvriders** [AnthonMS/my-cards#14]
![Screenshot_20220118-230836_Chrome](https://user-images.githubusercontent.com/26294678/150067858-342bdc68-0400-45b3-8f1c-58be5b41e35d.jpg)

**Comment by TheTimeWalker** [comment]
Did you read the README at all?
https://github.com/AnthonMS/my-cards#hacs

**Comment by AnthonMS** [comment]
You'll have to add the repository first. I haven't been working on getting it in HACS as default. Didn't really think this many people would be using it.

**Comment by TheTimeWalker** [comment]
@AnthonMS Maybe because the slider is now used for [Minimalist UI](https://ui-lovelace-minimalist.github.io/UI/setup/download/#prerequisites_1) 😄
