### ISSUE TITLE
Cant install via HACS

### ISSUE THREAD

**Issue by mcdent** [AnthonMS/my-cards#15]
Not sure what I am doing wrong? I've installed other repos in to HACS ok?

"Repository structure for main is not compliant"

![Screenshot 2022-01-24 at 20 51 01](https://user-images.githubusercontent.com/8769856/150863036-1ec80e3a-1c8e-44f4-8ce9-1a024b69baac.jpg)

**Comment by TheTimeWalker** [comment]
You selected Integration instead of Frontend

**Comment by AnthonMS** [comment]
If you're unsure, look at Issue #17. I have given a detailed explanation there.
