### ISSUE TITLE
Bug with initial value when minSet and maxSet are set

### ISSUE THREAD

**Issue by jncanches** [AnthonMS/my-cards#2]
Hi,
great card !
There is a bug when using minSet and maxSet. In this case (for example using a light with Warmth function, the slider is not initialized with the right value, event when the value is set between min and max sets.
I found a correction updating the template used. Instead of this
`					<ha-card>
						<div class="slider-container" style="${styleStr}">
							<input name="foo" type="range" class="${entity.state}" style="${styleStr}" .value="${entity.state === "off" ? 0 : entity.attributes.color_temp}" min="${entity.attributes.min_mireds}" max="${entity.attributes.max_mireds}" step="${step}" @change=${e => this._setWarmth(entity, e.target, minSet, maxSet)}>
						</div>
					</ha-card>`

use 
`					<ha-card>
						<div class="slider-container" style="${styleStr}">
							<input name="foo" type="range" class="${entity.state}" style="${styleStr}"  min="${entity.attributes.min_mireds}" max="${entity.attributes.max_mireds}" step="${step}" .value="${entity.state === "off" ? 0 : entity.attributes.color_temp}" @change=${e => this._setWarmth(entity, e.target, minSet, maxSet)}>
						</div>
					</ha-card>`

Just write .value attribute after min and max ones.

Hope this helps.

**Comment by AnthonMS** [comment]
And I'm guessing this piece is only for the warmth. Is the bugs also present when using just brightness? Because if it does, then this needs to be added in all the different sliders.

**Comment by jncanches** [comment]
It is not about adding some code but only reorganize the order of attributes in the input element.
I don't know why it is working ( probably a problem with events triggered on the input before all attributes are set. Weird but I can't see a better explanation)
Sorry I haven't test this behavior with other slider but we can reasonnably expect the same behavior so I would do the change for all of them.

Hope this helps

**Comment by jncanches** [comment]
I can do a merge request. But can you send me the command line to build the project before push ?

**Comment by AnthonMS** [comment]
Yeah just the npm command, sorry for not specifying.

Ohh really? To be honest, I actually don't know much git, and I have never personally made a PR for another project, so I don't know much about it. On the last repo, a guy made a lot of PR's with some great updates to the card, but I have no idea how he made the PR's, I just know how to accept, delay and deny them when they are incoming.

But I can very quickly update it directly on github I suppose with their new VSCode webview.

**Comment by jncanches** [comment]
Generally, to made a PR, you first create a branch, commit on it and push it to Git. 
On github you use the "pull request" tab and "create pull request" button with your "master" branch (called "main" on my-cards projects) as base branch and the new branch (the one with the fix) as the compare branch.

I have make the branch, commit it but I cannot push it to your github. I think you have to authorize my login on your project as a developper (don't the exact term on Github, I am more confortable and used to Gitlab, but the basics are the same)

**Comment by AnthonMS** [comment]
Yeah okay. But I usually don't have to authorize people to make PRs. You only authorize them if they need to be able to directly pull/push changes. Normally I just have to accept the PRs.

But I have made the change really quick, I hope it fixes the issue. Otherwise let me know.
