### ISSUE TITLE
Hide slider when off

### ISSUE THREAD

**Issue by guy0nabuffalo** [AnthonMS/my-cards#22]
Hello,
Could you add the option to hide the slider when the entity is off?

**Comment by AnthonMS** [comment]
If you mean you would like to hide the entire card? I can add this in the new my-slider-v2 card if it's still desired?

**Comment by guy0nabuffalo** [comment]
Hello,
This request was for the original slider card. My thought was to have only the slider part of the card be hidden when the entity is off (as a means to save screen space). I see you are now creating a v2 which looks different, so I dont think this request would apply.
Thanks anyway!
