### ISSUE TITLE
Vertical slider not responding on IOS touch devices

### ISSUE THREAD

**Issue by AnthonMS** [AnthonMS/my-cards#29]
The new slider does not work vertically on IOS touch devices. I am aware of this and I will be figuring out how to debug and fix it without having access to a mac og iphone.

Any insight is welcome.

**Comment by AnthonMS** [comment]
When I run some tests through LambdaTest, then the slider-v2 doesn't work at all on safari. I get the evaluating t.path.find error.
I will do some more testing. This was just a weird first test result.

**Comment by AnthonMS** [comment]
PR #32 should have fixed this, but it is still not working on iPadOS.

**Comment by AndyVRD** [comment]
Just clearing out, V2 is working fine on iPadOS15 and iPadOS16 beta 2. I told Anthon it was not working but it seems to be a cache issue. Finally iOS, iPadOS and Safari users can now use the slider anywhere instead of using the Thumb. Great work guys!

**Comment by AnthonMS** [comment]
Fixed in PR #32
