### ISSUE TITLE
[Bug]: Thumb stuck wen flipped: true

### ISSUE THREAD

**Issue by AndyVRD** [AnthonMS/my-cards#34]
### Current Behavior

Wen you set the flipped mode true (for cover entities...) it's stuck at the top of the slider wen moving the slider.

### Expected Behavior

Thumb following the slider position.

### Steps To Reproduce

Set flipped: true wen using a vertical slider.

### Environment

```markdown
- OS: haos_rpi4-64
- Node: Chrome, Firefox, iOS, iPadOS, ...
- Version: v1.0.2 (My-slider-v2)

Home Assistant 2022.8.4
Supervisor 2022.08.3
Operating System 8.4
Frontend-versie: 20220802.0 - latest
```

**Comment by AnthonMS** [comment]
Hmm weird. I use the card for cover entities myself.
