### ISSUE TITLE
[Bug]: <Can't add to repository.>

### ISSUE THREAD

**Issue by MrOnve** [AnthonMS/my-cards#35]
### Current Behavior

I can't add to repository
![bug](https://user-images.githubusercontent.com/111525932/186039340-8bed6a6f-d621-450f-814f-63f6d0ba623d.PNG)
.

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by tracestep** [comment]
Yeah, my sliders stopped working after an update. I tried removing and re-adding the repository, now I am getting "Repository structure for v1.0.2 is not compliant" when I try to re-add a custom repository to HACS.

**Comment by Bigegg2020** [comment]
I'm getting the same error when trying to add the repository via the "three dots" in top right hand corner.

**Comment by DeadlyHD** [comment]
> 

Ever get this solved?

**Comment by SecretFinder** [comment]
I have the same issue. Attempting to add the repo gives the error `Repository structure for v1.0.2 is not compliant`
![2022-09-24_21h40_30](https://user-images.githubusercontent.com/87812829/192095983-98ad45da-8b0a-4463-9265-c3971305c525.png)

**Comment by joeu1998** [comment]
This is still an issue for me, too - "structure for v1.0.2 is not compliant"

**Comment by SecretFinder** [comment]
Interestingly I tried adding the repo on a whim today and it worked. I haven't touched or changed anything with my install, but it worked.
Might be worth giving it a go.

**Comment by AnthonMS** [comment]
I don't know. I am not the one that have set up HACS compliance and HACS has thrown errors in my own setup for over a year now. So I can't help with this at the moment.

You will have to download the latest releases and do manually installs and updates.

**Comment by AnthonMS** [comment]
I am personally using the card through HACS when I am not developing on it. It updated fine to the latest release. It should work through HACS: If there is still issues create a new one explaining what the problem is.
