### ISSUE TITLE
[Feature]: Support tilt for covers in my-slider

### ISSUE THREAD

**Issue by Atokulus** [AnthonMS/my-cards#36]
### Is your feature request related to a problem?

There are many covers, such a blinds, available in Home Assistant supporting tilt operations. Currently `my-slider` does not support tilt operation on covers.

### Describe the solution you'd like

Extend the parameters of `my-slider` to support

```yaml
coverMode: 'tilt'
```

The slider then allows to set the tilt.

**Comment by AnthonMS** [comment]
Thank you for the suggestion and further contributions. I have merged the change and updated the readme for my-slider-v2
