### ISSUE TITLE
Issue in vertical

### ISSUE THREAD

**Issue by ldsmovil** [AnthonMS/my-cards#4]
Hi, great card, im in a trouble implementing 5 covers in vertical

![image](https://user-images.githubusercontent.com/73847117/138491810-1c901e4f-7a6a-46d5-ae29-999567ce818d.png)

it doesnt fill the card in height

`type: horizontal-stack
cards:
  - type: custom:my-slider
    entity: cover.shelly_salon_1
    rotate: 90
    height: 300px
    show_warning: false
    show_error: false
  - type: custom:my-slider
    entity: cover.shelly_salon_1
    rotate: 90
    height: 300px
  - type: custom:my-slider
    entity: cover.shelly_salon_1
    rotate: 90
    height: 300px
  - type: custom:my-slider
    entity: cover.shelly_salon_1
    rotate: 90
    height: 300px
  - type: custom:my-slider
    entity: cover.shelly_salon_1
    rotate: 90
    height: 300px`

**Comment by Taraman17** [comment]
Hi,
this is exactly what I was looking for!

I also have the issue with vertical sliders and am currently trying to cope with it.
So any improvement here is appreciated.

I'm trying to place sliders on a picture elements card and the width/height conversion gets my brain twisted. ;-)

**Comment by AnthonMS** [comment]
Sorry that I haven't had time to look into this yet. "Wife" get's in the way, as some of you know. This is a bigger feature than just fixing small stuff here and there. But I am looking into this. I hope I can come out with a better solution at some point.

**Comment by Taraman17** [comment]
How about making two seperate versions. like my-slider and my-slider-vertical.
That way you could switch width and height given in the config in the background and avoid the headache of finding out which is which from the rotation angle.
Also you could add an "invert" option then for shutters that have 100% on open.

**Comment by AnthonMS** [comment]
It is actually a relatively easy change to make height and width switched if the orientation is vertical. But I actually didn't think people were using the vertical setup. I remember spending way to long setting up my simple card with a vertical slider.

But I will implement this the next time I'm working on the card. I will also implement it so if the entity is of type cover, then invert the colors.

**Comment by dobby5** [comment]
I would also be very interested in the vertical slider and would be happy about an implementation.

I have made some changes to your example, maybe it will help someone:

```
type: custom:my-slider
entity: light.stehlampe
rotate: 270
toggle_scroll: true
top: calc(100% - 125px);
left: '-75px
height: 50px
containerHeight: 200px
width: var(--container-height);
radius: 5px
mainSliderColor: rgba(65, 65, 65, 0.5)
secondarySliderColor: rgba(255, 255, 255, 1)
thumbWidth: 4px
thumbHeight: var(--container-height);
thumbColor: rgba(65, 65, 65, 1)
thumbHorizontalPadding: 4px
thumbVerticalPadding: 0px
thumbTop: 0px
thumbBorderRight: 0px
thumbBorderLeft: 0px
thumbBorderTop: 0px
thumbBorderBotton: 0px
style: |
  ha-card {
    --ha-card-background: rgba(230, 230, 230, 0);
    border-radius: 5px;
    width: 50px
  }
```

The following must be set: "top", "left", "width" (ha-card) and "containerHeight".

**Comment by AnthonMS** [comment]
The new slider-v2 can easily be made vertical, flipped, inverted or all three at the same time.

I will close this issue since I will not be implementing that in the original html range input.
