### ISSUE TITLE
[Bug]: SLIDER V2 coverMode = Tilt is not working

### ISSUE THREAD

**Issue by martinmoravek** [AnthonMS/my-cards#44]
### Current Behavior

If you change coverMode to tilt, it still works only with position

There is missing this part of code

My cards version 1.0.2

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by AnthonMS** [comment]
There are a ton of stuff missing in the V2 still. I have overlooked quite a bit to be honest. I will take a look at this when I have time.

Thanks for reporting.

**Comment by AnthonMS** [comment]
This should have been added in the latest release.
