### ISSUE TITLE
[Feature]: Add step property to slider V2

### ISSUE THREAD

**Issue by mutzl** [AnthonMS/my-cards#46]
### Is your feature request related to a problem?

There is no `step` property in V2

### Describe the solution you'd like

like available in V1.

**Comment by alexandrechoske** [comment]
Waiting for this implementation!

**Comment by AnthonMS** [comment]
There is a step in Slider v2 I just forgot to update Readme. It will not "show" the steps in the slider, but it will only update the entity if the slider has crossed the step boundary. I am thinking of implementing a way of telling the slider to show steps or not. But there is some Step functionality.

**Comment by AnthonMS** [comment]
Closing because duplicate #27

**Comment by panhans** [comment]
I just wonder how to set step size. I have an _input_number_ with step size 0.5 but the slider card v2 only support full steps. Values like e.g. 1.5 are not possible.
