### ISSUE TITLE
[Bug]: Slider not working on 'Internal URL' connection on iOS and Safari

### ISSUE THREAD

**Issue by pauloruberto** [AnthonMS/my-cards#47]
### Current Behavior

I know this is going to sound crazy and I have no idea why this might be happening, but the sliders only work when I'm connected to my External URL via NabuCasa on both iOS (companion app) and Safari.

I've attached a screen recording example on Safari, where you can see the Internal connection on the left.

### Expected Behavior

Slider should work for both internal and external URLs

### Steps To Reproduce

* Connect to Internal URL, sliders don't slide
* Swap companion app or Safari to ExternalU URL, works as expected

### Environment

```markdown
- OS: iOS 16.4 beta, macOS 13.2, Safari 16.3
- App Version: 2023.2
- Hassio: 2023.3.3
```

### Anything else?

https://user-images.githubusercontent.com/10248306/224380763-9bda1ced-be8a-4afa-97bd-5ab0f41eb848.mp4

**Comment by AnthonMS** [comment]
Hmm.. I'm really scratching my head about this one. I don't have any apple products to really test it on those devices. It makes it really tedious to debug. But it is of course something I will try to reproduce and figure out when I get time.

Thanks for reporting it.

**Comment by AnthonMS** [comment]
I'm thinking it's the way the card is imported to Home Assistant maybe. I can't see how this can be a problem in the code of the card to be honest.

**Comment by pauloruberto** [comment]
Interestingly enough, didn't change anything on my end and it started working on its own a little while back. I'm assuming some HA release fixed it 😅thanks for digging into it though
