### ISSUE TITLE
[Feature]: Slider for cards too

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [AnthonMS/my-cards#50]
### Is your feature request related to a problem?

I currently have 2 cards that should move together but with the current slider code I can only have a slider for single entities and not a vertical-stack card. In my case I have the garage cover button and the garage camera and I want to be able to have more in a slider for other garages.

### Describe the solution you'd like

Be able to  create a slider that can, instead of an entity, use a car (vertical-card for example)

**Comment by AnthonMS** [comment]
Hello, thank you for the input. 

I'm uncertain what it is you are trying to do.

If you want a vertical card with multiple sliders in it, then you just put the slider-card inside of the vertical card? It's a card like any other.
