### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by sr-as2** [AnthonMS/my-cards#51]
### Current Behavior

Hi
When i'm scrolling on my lovelace dashboard, accidentally this turns on the lights via the slider.
Cela semble pourtant être un problème corrigé de ce que j'ai lu dans les issues

### Environment

```markdown
My Cards Bundle v1.0.3
```

**Comment by AnthonMS** [comment]
Not sure what you mean, but try playing around with the config for allowTapping, allowSliding and such. Or come back with a more in depth issue.
