### ISSUE TITLE
[Feature]: Using Slider as Media Player Seek Bar.

### ISSUE THREAD

**Issue by sharn25** [AnthonMS/my-cards#52]
### Is your feature request related to a problem?

Yes, I want to use in my custom card for google home.

### Describe the solution you'd like

Able to map the seek bar to Media Player Seek bar.

**Comment by AnthonMS** [comment]
I have no idea what a seek bar is. I'm sorry?

**Comment by sharn25** [comment]
Seek bar is the bar in the music player which tells how music song is played and we can change the position to adjust the song playing time.

**Comment by AnthonMS** [comment]
Ahh that makes sense, and actually a very good suggestion! Will keep in mind when developing new features for the slider-v2.

**Comment by AnthonMS** [comment]
Should be working in the latest release. Let me know if there are any issues.
