### ISSUE TITLE
[Feature]: <Value of Slider shown in text>

### ISSUE THREAD

**Issue by crankycowboy** [AnthonMS/my-cards#55]
### Is your feature request related to a problem?

No, this is a request

### Describe the solution you'd like

I saw that previously you indicated you had hoped to implement the value of the slider in V2, but I can't find where I can include that. I was hoping something similar to what is in the "entity row" slider but with the cool slider you have created.

**Comment by AnthonMS** [comment]
I'm thinking this is duplicate of #23 

So I'll be closing this one. It is one the todo list.
