### ISSUE TITLE
Can't find my-cards in HACS

### ISSUE THREAD

**Issue by DeTimm** [AnthonMS/my-cards#7]
Hello,

Can't find my-cards in HACS. Is it possible to add manually?
![2021-12-02_13h28_50](https://user-images.githubusercontent.com/59252855/144422106-1b1e138a-c497-47b8-bd8f-723844df8fb2.png)

**Comment by AnthonMS** [comment]
Hello,

Yes I don't know how to get my repository into HACS database. To be honest, I haven't really researched it that much.

But you can put this repository into HACS as a custom repository. So just copy paste this link underneath into the custom repo popup in HACS.
![image](https://user-images.githubusercontent.com/23500433/144424664-c44068b2-7c01-4c84-b8aa-e5b311bb6ecf.png)
![image](https://user-images.githubusercontent.com/23500433/144424744-486a4594-a08b-4e6c-9583-6adaf790e5ef.png)

https://github.com/AnthonMS/my-cards.git

When you have done this, then you'll be able to find the card in HACS.

**Comment by DeTimm** [comment]
Thanks it works! Let the fun begin.

**Comment by AnthonMS** [comment]
I hope you have fun and don't pull out all your hair, because of frustration in the cards config. Some of the settings are a little buggy and tricky to get right. This is the first thing I ever made for HA, and I have a hard time getting away from my spaghetti code.

**Comment by TheTimeWalker** [comment]
> Yes I don't know how to get my repository into HACS database. To be honest, I haven't really researched it that much.

It should be pretty simple. You first have to check with two Github Actions that your code and HACS information is correct. Then you just open a PR on https://github.com/hacs/default
See more here: https://hacs.xyz/docs/publish/include

**Comment by AnthonMS** [comment]
> It should be pretty simple. 

Thanks, I'll check it out the next time I'm messing with the card.
