### ISSUE TITLE
Can't find in HACS

### ISSUE THREAD

**Issue by techtomydoor** [AnthonMS/my-cards#8]
I'm setting up UI-Lovelace-Minimalist "Theme" and am unable to find my-cards in HACS. Yes, I've clicked the + in the lower right corner in HACS. Any idea why my-cards would not show up in a search in HACS? Thanks in advance!

**Comment by AnthonMS** [comment]
Wrong add repo button. 

I give it to you, it's not obvious it's the wrong one at first. But with that said, it would have been made clear, if you just tried to click on one of the other add repo buttons.

Find the closed issue where I describe where you find the correct add repo button.

Please don't use me as google.

**Comment by techtomydoor** [comment]
I'm so embarrassed. Please accept my apology. I was in a rush and did not look at the closed issues. Lost my mother to COVID this week while in the middle of setting this up and am just getting back to it as something to keep my mind occupied. Clearly not the time to be trying to do anything detail-oriented. Sorry again for the asking the ridiculous question! Thank you for your contributions and for the quick reply to my issue!

**Comment by AnthonMS** [comment]
Oh my lord, now I feel so bad! I'm sorry that my response was a bit snappy. I just found it interesting that this question was almost the exact same title as the one right underneath it.

Of course you can ask questions about my card. Also if you're having trouble setting it up, please don't hesitate to create another issue with your question. There aren't many issues, so it's not likely you will create another duplicate :)

And my sincere condolences to you and your family! I can't even begin to imagine what that feels like. Please reach out to someone if you're feeling overwhelmed, even if it's just a new issue where you rant about how shitty the card is. You have my permission to rip it apart, if it can distract you just a bit. :)

**Comment by techtomydoor** [comment]
LOL! I wish we could meet in person, I know we would be pals. Not at all my intention to make you feel bad and I would have replied to my first question in much the same way. I laughed out loud when I looked at the closed issues and I literally duplicated the exact same question. DOH!!! I'm usually pretty good about thoroughly Googling before asking.

Quick story... My dog died in January as I was putting together a quotation for a customer and I figured "it's just the dog, I'm fine" so I finished the quotation and sent it. A few days later the customer called and asked if we could go through the quotation on the phone together. As I opened it and looked, none of it made any sense. I apologized and explained what had happened. My customer is awesome and he let me re-work the proposal and gave some advice to take as much time as necessary as he has lost many dogs in his lifetime and each loss impacted him as much as any other family member.

So I'm learning from that experience and not doing anything really critical right now. But I do need to keep my mind occupied and move forward so I figured it was a good time to mess about in Home Assistant doing all that stuff we all want to do but never seem to have the time to do. And immediately learned that my mind is foggy. LOL

I really appreciate your quick response and condolences. And I applaud your work and putting it out there for the rest of us to implement in our setups! I know just enough code to make a big mess of things so kudos to you for creating this!

**Comment by AnthonMS** [comment]
I'm sure we would, you seem like a super chill person who could teach me some of that. LOL.

But I'm glad to hear that you are aware of everything going on and that you are taking the steps you need, to deal with this trauma. Each person is different, so it's good, that you know what you need to keep going forward and not get stuck. I know I would be lost, if put in your shoes. So I'm the one applauding :)

But thanks for your kind words. It always makes me happy, to know another person find, what I made, helpful.
