### ISSUE TITLE
problemer med "Warmth"

### ISSUE THREAD

**Issue by MicServerKonto** [AnthonMS/my-cards#9]
When I use

Adjust Warmth of Light
cards:
  - type: custom:my-slider
    entity: light.example
    function: "Warmth"

then it does not work,
when I create it, it puts the slider where it's currently set to,
but when I then move and release it, it gets stuck in the left side

**Comment by AnthonMS** [comment]
Which lights are you using?
What services do you call to set warmth on that specific light?

I think it's because different lights handle the warmth parameter differently, and I have only had lights with warmth from Ikea through DeConz. But I'm happy to implement you're lights as well if you can give me a screenshot of the light entities attributes from HA developer tools and if you can list which services it has to set warmth.

**Comment by MicServerKonto** [comment]
I use wiz light bulb (wifi) and ledstrip Livarno (zigbee) from Lidl
![led_strip](https://user-images.githubusercontent.com/92755623/154845107-1862b830-ccb4-4ef2-8480-9387f0f1a4f1.PNG)
![Wiz_1](https://user-images.githubusercontent.com/92755623/154845287-773ea582-854c-4c26-9742-97ed0ff4cc9a.PNG)
![Wiz_2](https://user-images.githubusercontent.com/92755623/154845288-a67cdc15-b023-452c-936a-d1ecb09252a4.PNG)

i just use a lovelace card: 
type: custom:my-slider
entity: light.strip_living_room
function: Warmth

I don't now what you mean by "list which services it has to set warmth" or how to find it ?

**Comment by PaulMcMillan** [comment]
I also see this issue with Hue bulbs through Zigbee2Mqtt, which works similarly to the bulbs above - color_temp is expected to be adjusted in mireds, which for my particular light range from 153 to 500.

**Comment by AnthonMS** [comment]
Okay. I think I will be able to figure out which service to call. I set up the warmth integration with a single Ikea zigbee bulb. And I guess there are different ways of setting warmth depending on which light it is and I can see there are also different ranges of warmth for each light, which is determined by the min_mireds and max_mireds. 

I will have a look at this next time I'm working on this card. But I can't say when I will be able to look at this card. I apologize.

**Comment by AnthonMS** [comment]
Did this ever get resolved? I'm pretty sure it did. I will close it until someone yells at me for forgetting all about it. Sorry.

**Comment by cymone-smart** [comment]
The behavior I experience when using my-slider that the initial display shows the proper slider position based on the color_temp of the device; however, when I attempt to adjust the color_temp level, the slider repositions to the minimum level and sets the color_temp of the device to the minimum value (color_temp: 153). The devices I am testing are Hue recessed color lights (with current firmware) and Hue color lightstrips (also with updated firmware) integrated via Zigbee2MQTT.
